# -*- coding: utf-8 -*-
"""soft&comp project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_QXRwyAxPUNVHinUX-AizcytJ-4zbJtZ

<font color='green'>**Satellite Image Classification (CNN Project)**</font>

**1 - Download and dataset path configuration**
"""

#Import libraries
import os
import kagglehub
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Input, Conv2D, MaxPooling2D, Flatten, Dense, Dropout

#Download dataset
print("Downloading Satellite Image Classification dataset...")
path = kagglehub.dataset_download("mahmoudreda55/satellite-image-classification")
print("Dataset downloaded to:", path)

#Inspect directory structure to locate the image folders
print("Contents of root folder:", os.listdir(path))

"""**2 - Loading and preprocessing the dataset**

Unlike pre-split datasets like MNIST, this dataset consists of class subfolders; the code automatically loads the images, maps the 4 classes, and splits them into training and validation sets.
"""

IMG_SIZE = (64, 64)
BATCH_SIZE = 32

#The actual images are in a subdirectory named 'data'
dataset_images_path = os.path.join(path, 'data')

#Load training dataset (using 80% of data for training, with validation split)
train_ds = tf.keras.utils.image_dataset_from_directory(
    dataset_images_path,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    label_mode='categorical',
    validation_split=0.2,
    subset="training",
    seed=123
)

#Load validation dataset (remaining 20%)
val_ds = tf.keras.utils.image_dataset_from_directory(
    dataset_images_path,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    label_mode='categorical',
    validation_split=0.2,
    subset="validation",
    seed=123
)

class_names = train_ds.class_names
num_classes = len(class_names)
print(f"Detected Classes ({num_classes}): {class_names}")

#Optimize data loading performance using caching and prefetching
AUTOTUNE = tf.data.AUTOTUNE
train_ds = train_ds.cache().prefetch(buffer_size=AUTOTUNE)
val_ds = val_ds.cache().prefetch(buffer_size=AUTOTUNE)

#Normalization layer (scaling pixel values from [0, 255] to [0.0, 1.0])
normalization_layer = tf.keras.layers.Rescaling(1./255)
train_ds = train_ds.map(lambda x, y: (normalization_layer(x), y))
val_ds = val_ds.map(lambda x, y: (normalization_layer(x), y))

"""**3 - Plot one representative image for each of the 4 classes**"""

#Use the dataset directory path defined in the previous cell
print("Dataset root path:", dataset_images_path)

#List and sort the class subfolders
subfolders = sorted([f for f in os.listdir(dataset_images_path) if os.path.isdir(os.path.join(dataset_images_path, f))])
print("Found classes:", subfolders)

#Plot one image directly from each class folder
plt.figure(figsize=(12, 3))

for i, class_name in enumerate(subfolders):
    class_folder = os.path.join(dataset_images_path, class_name)
    images_in_folder = [f for f in os.listdir(class_folder) if f.lower().endswith(('.png', '.jpg', '.jpeg'))]

    if images_in_folder:
        #Pick the first image in the folder
        img_path = os.path.join(class_folder, images_in_folder[0])

        #Load and convert image
        img = tf.keras.utils.load_img(img_path, target_size=(64, 64))
        img_array = tf.keras.utils.img_to_array(img)
        img_array = np.clip(img_array, 0, 255).astype("uint8")

        plt.subplot(1, len(subfolders), i + 1)
        plt.imshow(img_array)
        plt.title(f"Class: {class_name}")
        plt.axis("off")

plt.tight_layout()
plt.show()

"""**4 - CNN model**"""

#Build the CNN model architecture
model = Sequential([
    Input(shape=(64, 64, 3)), # 3 color channels (RGB) for satellite images
    Conv2D(32, kernel_size=(3, 3), activation='relu'),
    MaxPooling2D(pool_size=(2, 2)),
    Conv2D(64, kernel_size=(3, 3), activation='relu'),
    MaxPooling2D(pool_size=(2, 2)),
    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.3),
    Dense(num_classes, activation='softmax') # Dynamically adapts to the 4 classes
])

#Compile model using accuracy to measure performance
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

#Display model summary structure
model.summary()

"""**5 - Train the model**"""

#Set the number of training epochs and train the model
EPOCHS = 10

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=EPOCHS
)

"""**6 - Evaluation & confusion matrix**"""

#Evaluate the model on the validation dataset and generate classification metrics
y_true = []
y_pred = []

for images, labels in val_ds:
    preds = model.predict(images, verbose=0)
    y_pred.extend(np.argmax(preds, axis=1))
    y_true.extend(np.argmax(labels.numpy(), axis=1))

y_true = np.array(y_true)
y_pred = np.array(y_pred)

print("\nClassification Report:")
print(classification_report(y_true, y_pred, target_names=class_names))

#Plot the confusion matrix using seaborn heatmap
cm = confusion_matrix(y_true, y_pred)
plt.figure(figsize=(7, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=class_names, yticklabels=class_names)
plt.title('Satellite image classification - Confusion matrix')
plt.xlabel('Predicted class')
plt.ylabel('True class')
plt.show()

"""**7 - Loss and accuracy plots (Training vs Validation)**

Plots training curves to demonstrate correct model convergence and monitor for overfitting.
"""

#Plot Training and Validation Loss & Accuracy curves
plt.figure(figsize=(9, 4))

#Loss plot
plt.subplot(1, 2, 1)
plt.plot(history.history['loss'], label='Training Loss', linewidth=2)
plt.plot(history.history['val_loss'], label='Validation Loss', linewidth=2)
plt.title('Model Loss per epoch')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)

#Accuracy plot
plt.subplot(1, 2, 2)
plt.plot(history.history['accuracy'], label='Training accuracy', linewidth=2)
plt.plot(history.history['val_accuracy'], label='Validation accuracy', linewidth=2)
plt.title('Model accuracy per epoch')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()

"""**8 - Prediction on a random image**

Picks a random image from the test set, performs model inference, and plots the result showing *True* vs *Predicted class*.
"""

import random

#Extract all images and labels from the validation dataset iterator
val_images = []
val_labels = []

for images, labels in val_ds:
    val_images.extend(images.numpy())
    val_labels.extend(labels.numpy())

val_images = np.array(val_images)
val_labels = np.array(val_labels)

#Pick a random index from the validation set
random_idx = random.randint(0, len(val_images) - 1)

single_image = val_images[random_idx]
true_label_idx = np.argmax(val_labels[random_idx])
true_class_name = class_names[true_label_idx]

#Prepare the image for the model prediction (add batch dimension: shape becomes (1, 64, 64, 3))
input_image_batch = np.expand_dims(single_image, axis=0)

#Perform model inference (prediction)
prediction_probs = model.predict(input_image_batch, verbose=0)
predicted_label_idx = np.argmax(prediction_probs[0])
predicted_class_name = class_names[predicted_label_idx]
confidence = prediction_probs[0][predicted_label_idx] * 100

#Plot the result
plt.figure(figsize=(4, 4))

#Rescale back to [0, 255] for plotting
plt.imshow(np.clip(single_image * 255.0, 0, 255).astype("uint8"))
plt.title(f"True: {true_class_name}\nPredicted: {predicted_class_name}\nConfidence: {confidence:.2f}%")
plt.axis("off")
plt.show()

"""**9 - Misclassification analysis**

This section identifies and displays a selection of misclassified validation images. For each image, the true label and the model's predicted label are shown, highlighting the classification errors.
"""

misclassified_indices = np.where(y_true != y_pred)[0]

print(f"Total number of misclassified images: {len(misclassified_indices)}")

#Display a few misclassified images
plt.figure(figsize=(15, 10))

#Choose how many misclassified images to display
num_display = min(10, len(misclassified_indices))

for i, idx in enumerate(misclassified_indices[:num_display]):
    plt.subplot(2, 5, i + 1)
    #Denormalize image for display (assuming normalization was 1./255)
    image_to_show = np.clip(val_images[idx] * 255.0, 0, 255).astype("uint8")
    plt.imshow(image_to_show)
    plt.title(f"True: {class_names[y_true[idx]]}\nPredicted: {class_names[y_pred[idx]]}", color='black')
    plt.axis("off")

plt.tight_layout()
plt.show()